/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adsocar.presentation.login.user;
import adsocar.domain.entities.Usuario;
import adsocar.domain.enums.RolUsuario;
import adsocar.domain.repositories.IUsuarioRepository;
import adsocar.infrastructure.repositories.UsuarioRepositoryImpl;
import adsocar.presentation.admin.AdminScreen; // Pantalla de Admin
import adsocar.presentation.user.UserCatalog;   // Pantalla de Usuario
import java.util.Optional; // Necesario para el resultado
import javax.swing.JOptionPane;

/**
 *
 * @author danielpacheco
 */
public class UserLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserLogin.class.getName());
private IUsuarioRepository usuarioRepo;
    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
        
        btnIniciarSesion.setOpaque(true);
        btnIniciarSesion.setContentAreaFilled(true);
        btnIniciarSesion.setBorderPainted(false); // Sin borde visual
        btnIniciarSesion.setFocusPainted(false);
        
        this.usuarioRepo = new UsuarioRepositoryImpl();

        // (Extra: Conectar el link de "Registrarse")
        linkRegistrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkRegistrarUsuarioMouseClicked(evt);
            }
        });
    }
    
    private void linkRegistrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
         new UserRegisterScreen().setVisible(true);
         this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logoadsocar1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        linkRegistrarUsuario = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        logoadsocar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoadsocar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adsocar/assets/Logo_adso_car.png"))); // NOI18N
        logoadsocar1.setText("jLabel1");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adsocar/assets/adsocar_letters.png"))); // NOI18N
        jLabel5.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoadsocar1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(logoadsocar1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 490));
        background.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 260, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 120, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("Ingresa tus datos");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 320, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Usuario:");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 120, 40));

        btnIniciarSesion.setBackground(new java.awt.Color(51, 153, 255));
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        background.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 210, 40));

        linkRegistrarUsuario.setForeground(new java.awt.Color(153, 153, 153));
        linkRegistrarUsuario.setText("¿No tiene una cuenta? Registrese");
        background.add(linkRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));
        background.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adsocar/assets/avatar.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 70, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        // 1. Recoger los datos
    // NOTA: Tu formulario pide "Email", pero tu repositorio busca por "nombreUsuario".
    // Asumiré que el campo "Email" en realidad se usa para el "nombreUsuario".
    String nombreUsuario = txtUsuario.getText(); //
    String contrasena = new String(txtContraseña.getPassword()); //

    if (nombreUsuario.isEmpty() || contrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar usuario y contraseña", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // 2. Buscar al usuario por su nombre de usuario
        Optional<Usuario> usuarioOpt = usuarioRepo.obtenerPorNombreUsuario(nombreUsuario);

        // 3. Verificar si el usuario existe
        if (!usuarioOpt.isPresent()) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Usuario usuario = usuarioOpt.get();

        // 4. Verificar la contraseña
        // (Reitero la ADVERTENCIA DE SEGURIDAD: esto compara texto plano)
        if (usuario.getContrasenaHash().equals(contrasena)) {
            // ¡Login exitoso!
            JOptionPane.showMessageDialog(this, "¡Bienvenido, " + usuario.getNombreCompleto() + "!", "Login Exitoso", JOptionPane.INFORMATION_MESSAGE);

            // 5. Redirigir según el ROL
            if (usuario.getRol() == RolUsuario.ADMINISTRADOR) {
                new AdminScreen().setVisible(true);
            } else {
                new UserCatalog().setVisible(true);
            }
            this.dispose(); // Cierra la ventana de login

        } else {
            // Contraseña incorrecta
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error al iniciar sesión", e);
        JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel linkRegistrarUsuario;
    private javax.swing.JLabel logoadsocar1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
