/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adsocar.presentation.admin;
import adsocar.presentation.admin.AddVehiculo;
import adsocar.presentation.admin.AdminScreen;// Para el botón Salir
import adsocar.presentation.admin.MenuAdminGestion;
/**
 *
 * @author USER
 */
public class AdminScreenVehiculos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminScreenVehiculos.class.getName());

    /**
     * Creates new form AdminScreenVehiculos
     */
    public AdminScreenVehiculos() {
        initComponents();
        
        btnAñadirVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirVehiculosActionPerformed(evt);
            }
        });
        
        // Botón "SALIR"
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        
        // Estilos para los botones
        btnAñadirVehiculos.setOpaque(true);
        btnAñadirVehiculos.setContentAreaFilled(true);
        btnAñadirVehiculos.setBorderPainted(false);
        btnAñadirVehiculos.setFocusPainted(false);
        
        btnSalir.setOpaque(true);
        btnSalir.setContentAreaFilled(true);
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        
        btnUsuarios.setOpaque(true);
        btnUsuarios.setContentAreaFilled(true);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setFocusPainted(false);
        
        btnEditarInfo.setOpaque(true);
        btnEditarInfo.setContentAreaFilled(true);
        btnEditarInfo.setBorderPainted(false);
        btnEditarInfo.setFocusPainted(false);
        
        btnEliminarV.setOpaque(true);
        btnEliminarV.setContentAreaFilled(true);
        btnEliminarV.setBorderPainted(false);
        btnEliminarV.setFocusPainted(false);
    }
    
    private void btnAñadirVehiculosActionPerformed(java.awt.event.ActionEvent evt) {
        new AddVehiculo().setVisible(true);
        this.dispose(); 
    }
    
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
        new AdminScreen().setVisible(true); // Vuelve a la pantalla principal de Admin
        this.dispose();
    }
private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {
        new MenuAdminGestion().setVisible(true); // Va a la gestión de usuarios
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAñadirVehiculos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnEliminarV = new javax.swing.JButton();
        btnEditarInfo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsuarios.setText("USUARIOS");
        jPanel3.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 141, 31));

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        jPanel3.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 425, 133, 34));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adsocar/assets/adsocar_letters.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 73));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 480));

        jLabel1.setText("Añade, Edita y Elimina informacion de los vehiculos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        btnAñadirVehiculos.setBackground(new java.awt.Color(0, 102, 204));
        btnAñadirVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAñadirVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirVehiculos.setText("AÑADIR VEHICULO");
        jPanel1.add(btnAñadirVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 180, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Gestion de Vehiculos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 250, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CÁTALOGO DE VEHICULOS"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarV.setBackground(new java.awt.Color(0, 102, 204));
        btnEliminarV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarV.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarV.setText("ELIMINAR DEL CATALOGO");
        btnEliminarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 36));

        btnEditarInfo.setBackground(new java.awt.Color(0, 102, 204));
        btnEditarInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarInfo.setText("EDITAR INFORMACIÓN");
        jPanel4.add(btnEditarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 32, 181, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adsocar/assets/carrito2 (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Modelo: Madza 3");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Año: 2019");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Kilometraje: 200.000");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Precio: $70.500.000");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 650, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 690, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminScreenVehiculos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirVehiculos;
    private javax.swing.JButton btnEditarInfo;
    private javax.swing.JButton btnEliminarV;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
